# These are supported funding model platforms

github: []  # Replace with GitHub sponsors
patreon: # Replace with Patreon username
open_collective: sales-agentic-army
ko_fi: # Replace with Ko-fi username
tidelift: # Replace with Tidelift platform-name/package-name
community_bridge: # Replace with Community Bridge project-name
liberapay: # Replace with Liberapay username
issuehunt: # Replace with IssueHunt username
otechie: # Replace with Otechie username
custom: ['https://sales-agentic-army.io/sponsor']
